src/_project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("vueforms/", include("vueforms.urls")),
    path("", include("core.urls")),
]

src/core/urls.py
from django.urls import path

from . import views as core_views

app_name = "core"

urlpatterns = [
    path("", core_views.home_view, name="home"),
]

src/vueforms/urls.py
from django.urls import path

from . import views as vue_views

app_name = "vueforms"

urlpatterns = [
    path(
        "", vue_views.IntelligentSearchSettingsView.as_view(), name="intelligent_search"
    ),
]

src/core/models/content_types.py
from django.core.exceptions import ValidationError
from django.db import models


class ContentType(models.Model):
    key = models.CharField(max_length=128, editable=True)
    name = models.CharField(max_length=255, unique=True)
    name_plural = models.CharField(max_length=255)

    def clean(self):
        if self.key and self.key != self.key.lower():
            raise ValidationError({"key": "The ID must be in lowercase."})

    def __str__(self):
        return self.name

src/core/models/groups.py
import uuid

from django.db import models


class Group(models.Model):
    id = models.UUIDField(primary_key=True, editable=False, default=uuid.uuid4)
    name = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return self.name

src/vueforms/models/intelligent_search.py
from django.db import models


class IntelligentSearchSetup(models.Model):
    name = models.CharField(max_length=255, unique=True)
    url = models.CharField(max_length=255, unique=True)
    shared_secret = models.CharField(max_length=128)
    index_setup = models.JSONField(null=True, blank=True)

    def __str__(self):
        return self.name

src/core/views.py
from django.shortcuts import render


def home_view(request):
    return render(request, "pages/home.html")

src/vueforms/views/intelligent_search.py
from django import forms
from django.urls import reverse
from django.views.generic import FormView

from vueforms.models.intelligent_search import IntelligentSearchSetup


class SettingsForm(forms.Form):
    name = forms.CharField(label="Name", max_length=255, required=True)
    url = forms.URLField(label="URL", max_length=255, required=True)
    shared_secret = forms.CharField(
        label="Shared secret", max_length=128, required=True
    )
    index_setup = forms.JSONField(label="Index setup", required=False)

    def __init__(self, *args, intelligent_search=None, **kwargs):
        self.intelligent_search = intelligent_search
        kwargs["initial"] = {
            "name": intelligent_search.name if intelligent_search else "",
            "url": intelligent_search.url if intelligent_search else "",
            "shared_secret": intelligent_search.shared_secret
            if intelligent_search
            else "",
            "index_setup": intelligent_search.index_setup
            if intelligent_search
            else None,
        }
        super().__init__(*args, **kwargs)

    def save(self):
        if not self.intelligent_search:
            self.intelligent_search = IntelligentSearchSetup()

        self.intelligent_search.name = self.cleaned_data["name"]
        self.intelligent_search.url = self.cleaned_data["url"]
        self.intelligent_search.shared_secret = self.cleaned_data["shared_secret"]
        self.intelligent_search.index_setup = self.cleaned_data["index_setup"]
        self.intelligent_search.save()


class SettingsView(FormView):
    template_name = "intelligent_search/settings.html"
    form_class = SettingsForm

    def get_form_kwargs(self):
        return {
            **super().get_form_kwargs(),
            "intelligent_search": IntelligentSearchSetup.objects.first(),
        }

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse("vueforms:intelligent_search")

src/core/templates/pages/home.html
{% extends 'page.html' %}

{% block head_title %}
    {{ block.super }} | Home
{% endblock %}


{% block page_content %}
    <div class="row mt-3">
        <div class="col">
            <h1>Welcome home!</h1>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <div class="card">
                <h5 class="card-header">
                    Home Page
                </h5>
                <div class="card-body">
                    <p>This is a simple home page for the application.</p>
                    <ul>
                        <li>
                            <a href="{% url "vueforms:intelligent_search" %}">VueForms Settings</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

src/shared/templates/page.html
{% extends 'root.html' %}

{% block content %}
    <div class="container">
    {% block page_content %}
    {% endblock %}
    </div>
{% endblock %}

{% block meta %}
    {{ block.super }}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-LN+7fdVzj6u52u30Kp6M/trliBMCMKTyK833zpbD+pXdCLuTusPj697FH4R/5mcr" crossorigin="anonymous">
{% endblock %}

{% block script %}
    {{ block.super }}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ndDqU0Gzau9qJ1lfW4pNLlhNTkCfHzAVBReH9diLvGRem5+R9g2FzA8ZGN954O5Q"
            crossorigin="anonymous"></script>
{% endblock %}

src/shared/templates/root.html
<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE }}">
<head>
    {% block meta %}{% endblock %}
    <title>{% block head_title %}{{ SITE_NAME }}{% endblock %}</title>
</head>
<body>
{% block content %}{% endblock %}
{% block script %}{% endblock %}
</body>
</html>

src/vueforms/templates/intelligent_search/settings.html
{% extends "page.html" %}

{% load vueforms %}
{% load custom %}
{% load core %}
{% load i18n %}

{% block page_content %}
    <h1>Intelligent search settings</h1>
    {% if form.errors %}
        <div class="alert alert-danger">
            <ul>
                {% for field, errors in form.errors.items %}
                    <li>
                        <strong>{{ field|capfirst }}:</strong>
                        {% for error in errors %}
                            {{ error }}
                        {% endfor %}
                    </li>
                {% endfor %}
            </ul>
        </div>
    {% endif %}
    <div class="card">
        <h5 class="card-header">
            Update intelligent search settings
        </h5>
        <div class="card-body">
            <form method="post" novalidate>
                {% csrf_token %}
                <div class="mb-2">
                    <label for="id_name" class="form-label">{{ form.name.label }}</label>
                    <input type="text" class="form-control" id="id_name" name="name"
                           value="{{ form.name.value|default_if_none:'' }}" required>
                </div>
                <div class="mb-2">
                    <label for="id_url" class="form-label">{{ form.url.label }}</label>
                    <input type="url" class="form-control" id="id_url" name="url"
                           value="{{ form.url.value|default_if_none:'' }}" required>
                </div>
                <div class="mb-2">
                    <label for="id_shared_secret" class="form-label">{{ form.shared_secret.label }}</label>
                    <input type="text" class="form-control" id="id_shared_secret" name="shared_secret"
                           value="{{ form.shared_secret.value|default_if_none:'' }}" required>
                </div>
                <div class="mb-2" id="index_setup_vue">
                    {% load_site_groups_for_select as all_groups %}
                    <h5>Index settings</h5>
                    <input type="hidden" id="id_index_setup" name="index_setup" :value="computedIndexSetup">
                    <div class="mb-2" v-for="(indexData, index) in indexSetup" :key="index"
                         v-show="!indexData?.isArchived">
                        <input type="hidden"
                               :id="`index_setup__${index}__is_archived`"
                               v-model="indexSetup[index].isArchived">

                        <select :id="`index_setup__${index}__guid`"
                                v-model="indexSetup[index].groupGuid"
                                class="form-select">
                            <option value="__nongroup__">
                                {% trans "Non group content" %}
                            </option>
                            <option value="__allsite__">
                                {% trans "All site content" %}
                            </option>
                            {% for id, name in all_groups %}
                                <option value="{{ id }}">
                                    {% blocktrans %}
                                        Group: {{ name }}
                                    {% endblocktrans %}
                                </option>
                            {% endfor %}
                        </select>
                        <div class="mt-2"><strong>Content types</strong></div>
                        <div class="row px-3">
                            <div v-for="(contentType, ctypeIndex) in allContentTypes" :key="ctypeIndex"
                                 class="form-check col-4">
                                <input type="checkbox"
                                       :id="`index_setup__${index}__content_types__${ctypeIndex}`"
                                       v-model="indexSetup[index].contentTypes[contentType]"
                                       class="form-check-input">
                                <label :for="`index_setup__${index}__content_types__${ctypeIndex}`"
                                       class="form-check-label">
                                    ({ contentType })
                                </label>
                            </div>
                        </div>
                        <div class="form-group d-flex justify-content-end mt-2">
                            <button class="btn btn-warning btn-sm"
                                    @click.prevent="remove_setting(index)">{% trans "Remove setting" %}</button>
                        </div>
                    </div>
                    <div>
                        <button class="btn btn-success"
                                @click.prevent="add_setting">
                            {% trans "Add setting" %}
                        </button>
                    </div>
                </div>
                <div>
                    <button class="btn btn-primary" type="submit">
                        Opslaan
                    </button>
                </div>
            </form>
        </div>
    </div>

{% endblock %}

{% block script %}
    {{ block.super }}
    <script src="{% vue_url %}"></script>
    <script>
        const {createApp, ref} = Vue
        const options = {
            delimiters: ['({', '})'],
            setup() {
            },
            computed: {
                computedIndexSetup() {
                    return JSON.stringify(this.indexSetup);
                }
            },
            data() {
                const data = {
                    indexSetup: JSON.parse({{ form.index_setup.value|as_json_string|safe }}) || [],
                    allContentTypes: JSON.parse('{% load_site_content_types_json %}'),
                }
                console.log(data)
                return data
            },
            methods: {
                add_setting() {
                    this.indexSetup.push({
                        groupGuid: '',
                        contentTypes: {},
                        isArchived: false,
                    })
                },
                remove_setting(index) {
                    this.indexSetup[index].isArchived = true;
                }
            },
            mounted() {
                console.log("Lets go");
            }
        };
        const app = createApp(options)
        app.mount('#index_setup_vue');
    </script>

{% endblock %}